### ISSUE TITLE
AES Encryption

### ISSUE THREAD

**Issue by Newbiedev39** [h3isenbug/url-locust#1]
HI!

I saw you had helped someone with some AES encryption in Go and was wondering if you'd be able to help me with it?

**Comment by h3isenbug** [comment]
Hi
https://dontasktoask.com/

**Comment by Newbiedev39** [comment]
Thanks for the reply. I have some [Java code ](https://i.imgur.com/gcuEEKa.png) and was wondering what would be the appropriate steps to replicate this decryption in Go? I tried normal PKCS7 decryption, but have had no luck. I saw you had replied to someone about BountyCastle (which is the `a` parameter in `Cipher.getInstance("AES/CBC/PKCS7Padding",a)`) and was hoping you'd be able to help.

Thank you so much for replying!

**Comment by h3isenbug** [comment]
It was years ago and I don't recall the details, but if you exactly tell Go and Java runtime the cipher alogirthm that you want, it will work.
Your provided a small part of the whole thing and I don't have the time to figure the rest out on my own.
You'll get your answer faster on stackoverflow or similar websites.

**Comment by Newbiedev39** [comment]
Thank you.

If you ever have free time, and would like to help me, please let me know. You will most definitely be compensated for your time. 

Thanks

**Comment by h3isenbug** [comment]
yw, if I had some free time, I would love to help :D
